### Configuration file for Neural PDE training

[data]
train = "data/data_train_nref4.h5" # file containing the training data
valid = "data/data_valid_nref4.h5" # file containing the validation data

[architecture]
dual_ref = 1              # number of refinements of dual mesh
n_radial = 4              # number of radial points on each patch
latent_dynamic_dim = 32   # dimension of dynamic latent space
latent_ancillary_dim = 16 # dimension of ancillary latent space
nt = 20                   # number of time steps
dt = 0.05                 # size of timestep 

[optimiser]
nepoch = 10000               # number of epochs
batchsize = 32               # size of training batches
initial_learning_rate = 0.01 # initial learning rate
final_learning_rate = 0.001  # final learning rate
