### Configuration file for Neural PDE training

[data]
train = "data/data_train_nref5.h5" # file containing the training data
valid = "data/data_valid_nref5.h5" # file containing the validation data

[architecture]
dual_ref = 1              # number of refinements of dual mesh
n_radial = 6              # number of radial points on each patch
decoder = "patch"         # decoder to use ('patch' or 'nearest_neighbour')
latent_dynamic_dim = 32   # dimension of dynamic latent space
latent_ancillary_dim = 16 # dimension of ancillary latent space
nu = 3                    # number of nearest neighours in decoder
dt = 0.01                 # Stepsize

[optimiser]
nepoch = 1024                # number of epochs
batchsize = 32               # size of training batches
initial_learning_rate = 0.005 # initial learning rate
final_learning_rate = 0.001  # final learning rate
